//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoktorKapisi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktorlar
    {
        public int Id { get; set; }
        public int BolumId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Resim { get; set; }
        public string Unvan { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
    }
}
